[CONTENT REVIEW] 9.3 - Atualização do Readme do projeto Shopping Cart
betrybe/sd-0x-project-shopping-cart pull request #16
Opened 2020-11-16 13:41 UTC by cleytonoliveira

Closes [#2247](https://github.com/betrybe/course/issues/2247)

2020-11-17 13:40 UTC, LizzardMedeiros requested changes

2020-11-17 13:40 UTC, LizzardMedeiros commented on README.md
> +Mostre a palavra "loading..." em algum lugar da página **apenas durante** a requisição à API. O elemento mostrado durante o carregamento da página deve, **obrigatóriamente**, ter a classe `loading`.
Acho interessante por alguma dica de implementação nesse requisito, não sei se foi corrigido, mas quando a T05 fez, tivemos que colocar um `setTimout` além da implementação básica para o avaliador "conseguir encontrar" o termo a tempo!

Se tiver sido corrigido esse bug, ignore esse review, se não, coloque como dia o uso do `setTimeout` para segurar o loading... alguns ms a mais!

2020-11-18 12:13 UTC, cleytonoliveira commented on README.md
> +Mostre a palavra "loading..." em algum lugar da página **apenas durante** a requisição à API. O elemento mostrado durante o carregamento da página deve, **obrigatóriamente**, ter a classe `loading`.
Boa @LizzardMedeiros, na turma 6 este problema já estava resolvido. Obrigado pelo tempo disponibilizado. Abraços

2020-11-19 13:24 UTC, LizzardMedeiros approved these changes

2020-12-14 12:24 UTC, roziscoding approved these changes

2020-12-14 12:24 UTC, merged